config/routes.rb
Rails.application.routes.draw do

  root "employees#index"
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_one_attached :profile_image
    validates :name, :joining_date, :email, :company_name, :position, presence: true
    validate :check_image_type

    private
    def check_image_type
        if profile_image.attached?
            if profile_image.content_type == "application/pdf"
                errors.add(:profile_image , "Plz upload jpeg, png images ")
            end
        else
            errors.add(:profile_image, "Image can't be blank")
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees = Employee.all
    end
    
    def show
        @employee = Employee.find(params[:id])
    end

    def new
        @employee = Employee.new
    end
    
    def create
        @employee = Employee.create(employee_params)
        if @employee.save
            EmployeeMailer.with(employee: @employee).welcome_email.deliver_later
            redirect_to @employee
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @employee = Employee.find(params[:id])
    end
    def update
        @employee = Employee.find(params[:id])
        if @employee.update(employee_params)
            redirect_to @employee
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @employee = Employee.find(params[:id])
        @employee.destroy
        redirect_to root_path
    end

    private
    def employee_params
        params.require(:employee).permit(:name, :joining_date, :company_name, :position, :profile_image, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_nav.html.erb
<nav class="navbar bg-white">
    <div class="container">
        <h4> Employee<span class="text-primary">Portal<span></h4>
        <div>
            <%= link_to "New Employee", new_employee_path, class:"btn btn-primary btn-sm" %>
        </div>
    </div>
</nav>

app/views/employees/edit.html.erb
<%= render "nav" %>
<h4 class="text-center mt-3"> Edit employee </h4>
<div class="container w-50 bg-white">
<%= form_with model: @employee do | form| %>
<div class="row">
    <div class="col-sm">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="col-sm">
        <%= form.label :position %>
        <%= form.text_field :position, class:"form-control" %>
    </div>
</div>
<div class="row">
    <div class="col-sm">
        <%= form.label :joining_date %>
        <%= form.date_field :joining_date, class:"form-control" %>
    </div>
    <div class="col-sm">
        <%= form.label :profile_image %>
        <%= form.file_field :profile_image, class:"form-control" %>
    </div>
</div>
<div class="row">
    <div class="col-sm">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control" %>
    </div>
</div>
<div class="row">
    <div class="col-sm">
        <%= form.label :company_name %>
        <%= form.text_field :company_name, class:"form-control" %>
    </div>
</div>
    <div><br>
    <%= form.submit class:"btn btn-success btn-sm" %>
    <%= link_to "Back", root_path, class:"btn btn-primary btn-sm" %>
    </div>
<% end %>
<br>
</div>

app/views/employees/index.html.erb
<%= render "nav" %>
<h4 class="text-center mt-3"> Employee listing </h4>
<div class="container">
<table class="table">
<thead>
    <th> Name </th>
    <th> Position</th>
    <th></th>
    <th></th>
    <th></th>
</thead>
<% @employees.reverse.each do | employee | %>
<tbody>
    <tr>
        <td><%= employee.name %></td>
        <td><%= employee.position %></td>
        <td><%= link_to "View", employee, class:"btn btn-success btn-sm" %></td>
        <td><%= link_to "edit", edit_employee_path(employee), class:"btn btn-warning btn-sm" %></td>
    </tr>
</tbody>
<% end %>
</table>
</div>

app/views/employees/new.html.erb
<%= render "nav" %>
<h4 class="text-center mt-3"> New employee </h4>
<div class="container w-50 bg-white">
<%= form_with model: @employee do | form| %>
<div class="row">
    <div class="col-sm">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
        <% @employee.errors.full_messages_for(:name).each do | message | %>
            <small class="text-danger"><%= message %></small>
            <% end %>
    </div>
    <div class="col-sm">
        <%= form.label :position %>
        <%= form.text_field :position, class:"form-control" %>
        <% @employee.errors.full_messages_for(:position).each do | message | %>
            <small class="text-danger"><%= message %></small>
            <% end %>
    </div>
</div>
<div class="row">
    <div class="col-sm">
        <%= form.label :joining_date %>
        <%= form.date_field :joining_date, class:"form-control" %>
        <% @employee.errors.full_messages_for(:joining_date).each do | message | %>
            <small class="text-danger"><%= message %></small>
            <% end %>
    </div>
    <div class="col-sm">
        <%= form.label :profile_image %>
        <%= form.file_field :profile_image, class:"form-control" %>
        <% @employee.errors.full_messages_for(:profile_image).each do | message | %>
            <small class="text-danger"><%= message %></small>
            <% end %>
    </div>
</div>
<div class="row">
    <div class="col-sm">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control" %>
        <% @employee.errors.full_messages_for(:email).each do | message | %>
            <small class="text-danger"><%= message %></small>
            <% end %>
    </div>
</div>
<div class="row">
    <div class="col-sm">
        <%= form.label :company_name %>
        <%= form.text_field :company_name, class:"form-control" %>
        <% @employee.errors.full_messages_for(:company_name).each do | message | %>
            <small class="text-danger"><%= message %></small>
            <% end %>
    </div>
</div>
    <div><br>
    <%= form.submit class:"btn btn-success btn-sm" %>
    <%= link_to "Back", root_path, class:"btn btn-primary btn-sm" %>
    </div>
<% end %>
<br>
</div>

app/views/employees/show.html.erb
<%= render "nav" %>
<h4 class="text-center"> Employee Details </h4>
<div class="container bg-white">
    <div class="row">
        <div class="col-sm-4 text-center">
            <%= image_tag(@employee.profile_image, size:"300x300" ,class:"rounded-circle border border-success border-5") if @employee.profile_image.attached? %>
        </div>
        <div class="col mt-4">
        <div >
        <%= link_to "edit", edit_employee_path(@employee) , class:"btn btn-primary btn-sm" %>
        <%= button_to "delete", employee_path(@employee), method: :delete, data:{
            turbo_confirm: "Are you sure?"
        }, class:"btn btn-danger btn-sm" %>
        </div>

            <table class="table">
                <tbody>
                    <tr>
                        <td><h5 class="fw-normal"> <b> Name :- </b><%= @employee.name %></h5></td>
                    </tr>
                    <tr>
                        <td><h5 class="fw-normal"> <b> Postion :- </b><%= @employee.position %></h5></td>
                    </tr>
                    <tr>
                        <td><h5 class="fw-normal"> <b> Joining_date :- </b><%= @employee.joining_date %></h5></td>
                    </tr>
                    <tr>
                        <td><h5 class="fw-normal"> <b> Company_name :- </b><%= @employee.company_name %></h5></td>
                    </tr>
                </tbody>
            </table>
            <%= link_to "Back", root_path, class: "btn btn-primary btn-sm" %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveJob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <%= yield %>
  </body>
</html>